// Used by src/screens/loginScreen.jsx
import { StyleSheet } from "react-native";
import { rf, rs } from "@/utils/responsive";

export const styles = StyleSheet.create({
  // Screen Background and Content Placement
  screen: { flex: 1, backgroundColor: "#FFFFFF", justifyContent: "center" },
  background: StyleSheet.absoluteFill,
  scroll: { flex: 1 },
  content: {
    flexGrow: 1,
    alignItems: "center",
    paddingHorizontal: rs(24, 16, 28),
    paddingTop: rs(80, 48, 88),
    paddingBottom: rs(280, 156, 280),
  },
  iosContent: {
    justifyContent: "center",
    paddingTop: rs(28, 20, 34),
    paddingBottom: rs(26, 18, 32),
  },
  keyboardContent: {
    justifyContent: "flex-start",
    paddingBottom: rs(220, 180, 240),
  },
  // Logo, App Name, and Tagline
  logo: { width: rs(169, 126, 176), height: rs(174, 130, 181) },
  title: {
    marginTop: 6,
    width: "100%",
    maxWidth: 360,
    textAlign: "center",
    fontFamily: "Angkor",
    fontSize: rf(38, 32, 40),
    lineHeight: rf(57, 48, 60),
    color: "#AF2532",
    includeFontPadding: false,
  },
  gold: { color: "#FEBF1F" },
  subtitle: {
    textAlign: "center",
    fontFamily: "AfacadFluxRegular",
    fontSize: rf(15, 14, 16),
    lineHeight: rf(22, 20, 24),
    color: "#000000",
    includeFontPadding: false,
  },
  // Welcome Message and Instructions
  welcome: {
    marginTop: rs(26, 16, 28),
    width: "100%",
    maxWidth: 352,
    textAlign: "center",
    fontFamily: "AfacadFluxSemiBold",
    fontSize: rf(24, 20, 25),
    lineHeight: rf(36, 30, 38),
    color: "#AF2532",
    includeFontPadding: false,
  },
  instructions: {
    marginTop: 8,
    maxWidth: 288,
    textAlign: "center",
    fontFamily: "AfacadRegular",
    fontSize: rf(16, 14, 16),
    lineHeight: rf(20, 18, 21),
    color: "rgba(0,0,0,0.53)",
    includeFontPadding: false,
  },
  // Shared Login Button Layout
  button: {
    width: "100%",
    maxWidth: 328,
    minHeight: rs(56, 50, 58),
    paddingVertical: rs(10, 8, 11),
    paddingHorizontal: rs(16, 12, 18),
    borderRadius: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: rs(10, 8, 12),
  },
  // Google and Guest Button Colors
  googleButton: {
    marginTop: rs(20, 14, 22),
    borderWidth: 1,
    borderColor: "#6C757D",
    backgroundColor: "#FFFFFF",
  },
  guestButton: { marginTop: rs(16, 12, 18), backgroundColor: "#AF2532" },
  iosFormButton: {
    backgroundColor: "#FFFFFF",
    borderColor: "#AF2532",
    borderWidth: 1,
    shadowColor: "#65111B",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 5,
  },
  iosGuestButton: {
    backgroundColor: "#8F1725",
    borderColor: "rgba(255,255,255,0.75)",
    borderWidth: 1,
    shadowColor: "#4F0811",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.22,
    shadowRadius: 10,
    elevation: 5,
  },
  // Login Button Labels
  buttonText: {
    fontFamily: "AfacadTextMedium",
    fontSize: rf(20, 17, 21),
    lineHeight: rf(30, 25, 31),
    includeFontPadding: false,
    flexShrink: 1,
  },
  googleText: { color: "#6C757D" },
  guestText: { color: "#FFFFFF" },
  iosFormButtonText: { color: "#AF2532" },
  // Login Button Icon Sizes
  googleIcon: { width: rs(35, 30, 36), height: rs(35, 30, 36) },
  guestIcon: { width: 21, height: 23 },
  // Button Press Feedback
  pressed: { opacity: 0.8 },
  primaryButtonDisabled: { opacity: 0.68 },
  modeToggle: {
    flexDirection: "row",
    gap: 8,
    width: "100%",
    maxWidth: 328,
    marginBottom: 14,
    padding: 4,
    borderRadius: 8,
    backgroundColor: "#F7E5E3",
  },
  modeButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    minHeight: rs(42, 38, 44),
    borderRadius: 6,
  },
  modeButtonActive: { backgroundColor: "#FFFFFF" },
  modeButtonText: {
    color: "#6C757D",
    fontFamily: "AfacadFluxSemiBold",
    fontSize: rf(14, 13, 15),
  },
  modeButtonTextActive: { color: "#AF2532" },
  input: {
    width: "100%",
    maxWidth: 328,
    minHeight: rs(48, 44, 50),
    marginBottom: 12,
    paddingHorizontal: rs(14, 12, 16),
    borderWidth: 1,
    borderColor: "#CDA6AA",
    borderRadius: 12,
    color: "#3C4147",
    fontFamily: "AfacadRegular",
    fontSize: rf(15, 14, 16),
    backgroundColor: "rgba(255,255,255,0.94)",
  },
  forgotPasswordButton: {
    alignItems: "flex-end",
    width: "100%",
    maxWidth: 328,
    marginTop: -4,
    marginBottom: 12,
    paddingVertical: 4,
  },
  forgotPasswordText: {
    color: "#AF2532",
    fontFamily: "AfacadFluxSemiBold",
    fontSize: rf(13, 12, 14),
  },
  privacyRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    width: "100%",
    maxWidth: 328,
    marginBottom: 14,
    padding: 10,
    borderRadius: 10,
    backgroundColor: "rgba(92, 12, 25, 0.72)",
    borderColor: "rgba(255,255,255,0.35)",
    borderWidth: 1,
  },
  checkbox: {
    alignItems: "center",
    justifyContent: "center",
    width: 22,
    height: 22,
    marginTop: 1,
    borderWidth: 1,
    borderColor: "#FFFFFF",
    borderRadius: 4,
    backgroundColor: "#FFFFFF",
  },
  checkboxChecked: { backgroundColor: "#AF2532" },
  checkboxText: { color: "#FFFFFF", fontSize: 13, fontWeight: "900" },
  privacyText: {
    flex: 1,
    color: "#FFFFFF",
    fontFamily: "AfacadFluxSemiBold",
    fontSize: rf(12, 11, 13),
    lineHeight: rf(17, 16, 18),
  },
  loginError: {
    color: "#AF2532",
    width: "100%",
    maxWidth: 328,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 10,
    borderColor: "#F0C7CC",
    borderWidth: 1,
    backgroundColor: "rgba(255,255,255,0.96)",
    fontSize: rf(14, 13, 15),
    fontFamily: "AfacadFluxSemiBold",
    lineHeight: rf(19, 18, 20),
    marginTop: 10,
    textAlign: "center",
    shadowColor: "#65111B",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.14,
    shadowRadius: 8,
    elevation: 3,
  },
});
