import { useFonts } from "expo-font";

export function useDesignFonts() {
  return useFonts({
    AfacadBold: require("../../assets/design/fonts/Afacad-Bold.ttf"),
    AfacadMedium: require("../../assets/design/fonts/Afacad-Medium.ttf"),
    AfacadRegular: require("../../assets/design/fonts/Afacad-Regular.ttf"),
    AfacadSemiBold: require("../../assets/design/fonts/Afacad-SemiBold.ttf"),
    AfacadFluxRegular: require("../../assets/design/fonts/afacad-flux-latin-400-normal.ttf"),
    AfacadFluxMedium: require("../../assets/design/fonts/afacad-flux-latin-500-normal.ttf"),
    AfacadFluxSemiBold: require("../../assets/design/fonts/afacad-flux-latin-600-normal.ttf"),
    AfacadFluxBold: require("../../assets/design/fonts/afacad-flux-latin-700-normal.ttf"),
    Angkor: require("../../assets/design/fonts/Angkor-Regular.ttf"),
    AfacadTextMedium: require("../../assets/design/fonts/Afacad-Medium.ttf"),
    CategoryBold: require("../../assets/design/fonts/afacad-flux-latin-700-normal.ttf"),
    CategoryRegular: require("../../assets/design/fonts/afacad-flux-latin-400-normal.ttf"),
    DetailBold: require("../../assets/design/fonts/afacad-flux-latin-700-normal.ttf"),
    DetailRegular: require("../../assets/design/fonts/afacad-flux-latin-400-normal.ttf"),
    DetailSemiBold: require("../../assets/design/fonts/afacad-flux-latin-600-normal.ttf"),
    HelpBold: require("../../assets/design/fonts/afacad-flux-latin-700-normal.ttf"),
    HelpRegular: require("../../assets/design/fonts/afacad-flux-latin-400-normal.ttf"),
    HistoryBold: require("../../assets/design/fonts/afacad-flux-latin-700-normal.ttf"),
    HomeBold: require("../../assets/design/fonts/afacad-flux-latin-700-normal.ttf"),
    HomeMedium: require("../../assets/design/fonts/afacad-flux-latin-500-normal.ttf"),
    HomeRegular: require("../../assets/design/fonts/afacad-flux-latin-400-normal.ttf"),
    HomeSemiBold: require("../../assets/design/fonts/afacad-flux-latin-600-normal.ttf"),
    LocationRegular: require("../../assets/design/fonts/afacad-flux-latin-400-normal.ttf"),
    LocationSemiBold: require("../../assets/design/fonts/afacad-flux-latin-600-normal.ttf"),
    NavigationMedium: require("../../assets/design/fonts/afacad-flux-latin-500-normal.ttf"),
    NotificationBold: require("../../assets/design/fonts/afacad-flux-latin-700-normal.ttf"),
    NotificationRegular: require("../../assets/design/fonts/afacad-flux-latin-400-normal.ttf"),
    NotificationSemiBold: require("../../assets/design/fonts/afacad-flux-latin-600-normal.ttf"),
    ProfileActionMedium: require("../../assets/design/fonts/afacad-flux-latin-500-normal.ttf"),
    ProfileMedium: require("../../assets/design/fonts/afacad-flux-latin-500-normal.ttf"),
    ProfileSemiBold: require("../../assets/design/fonts/afacad-flux-latin-600-normal.ttf"),
    SearchBold: require("../../assets/design/fonts/afacad-flux-latin-700-normal.ttf"),
    SearchRegular: require("../../assets/design/fonts/afacad-flux-latin-400-normal.ttf"),
  });
}
